### ISSUE TITLE
[ISSUE] Current Time Not Updating in Timetable

### ISSUE THREAD

**Issue by root-daemon** [Rahuletto/AcademiaPro#9]
The Green circle indicated in the timetable not updating as the time-changes. It is stuck in the time that it is initially updated 

**Expected behavior**
The time should update as per the current time of the day 

**Screenshots**
![image](https://github.com/Rahuletto/AcademiaPro/assets/47695678/dab88b8a-818f-4df8-ab73-517f2a2cdf8f)

**Comment by Rahuletto** [comment]
Fixing this issue with the commit https://github.com/Rahuletto/AcademiaPro/commit/f967a88f7c32827390b46410790e826341f3fcb7

## Reason
Happens because it takes the server time instead of the client sided time.
It occurs in initial render where we didn't get IST time, instead using UTC time. Using the React state fixes the issue
